# Generated by Django 5.1.7 on 2025-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.IntegerField(
                default=0,
                help_text="Введите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
