# Generated by Django 5.1.7 on 2025-03-27 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0002_product_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Опубликованность"),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="человекочитаемая ссылка",
                max_length=200,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
    ]
