# Generated by Django 5.1.7 on 2025-03-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0003_product_is_active_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(max_length=70, verbose_name="Наименование версии"),
                ),
                (
                    "version_number",
                    models.CharField(max_length=10, verbose_name="Номер версии"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Активная/Неактивная"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealer.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версии",
            },
        ),
    ]
